bytecodealliance/wasmtime-dotnet

.github/workflows/main.yml
This PR triggers the CI build every night to ensure that the upstream
Wasmtime repo doesn't break the build without detection.
=> Trigger CI every night.

.github/workflows/main.yml, tests/FunctionThunkingTests.cs
This will get CI green once bytecodealliance/wasmtime#1600 is merged (should be today).
=> Update expected trap message for backtrace.

src/Host.cs, tests/ModuleLoadTests.cs
This PR modifies `Host.LoadModuleText(string, Stream)` to leave the supplied stream open like `Host.LoadModule(string, Stream)` does.
It also includes tests to check this behavior for both of `LoadModule` and `LoadModuleText`.
=> Leave the supplied stream open in `LoadModuleText`

README.md, docs/articles/intro.md, examples/global/Program.cs, examples/hello/Program.cs, examples/memory/Program.cs, src/Host.cs, src/Interop.cs, src/Module.cs, src/Store.cs, src/StoreBuilder.cs, src/WasiConfiguration.cs, tests/Fixtures/ModuleFixture.cs, tests/FunctionThunkingTests.cs, tests/GlobalExportsTests.cs, tests/GlobalImportBindingTests.cs, tests/InvalidModuleTests.cs, tests/MemoryExportsTests.cs, tests/MemoryImportBindingTests.cs, tests/ModuleLoadTests.cs, tests/TableExportsTests.cs, tests/TrapTests.cs, tests/WasiSnapshot0Tests.cs, tests/WasiTests.cs
This is a breaking API change.
The `Host` class was split back into a `Store` type, where loading of modules
will occur.
This allows for loading modules into a single store and defining one or more
hosts that instantiate the modules without having to load the modules again.
Fixes #9.
=> Add the Store type back to the API.

.github/workflows/main.yml, .gitignore, README.md, benchmarks/simple/Program.cs, benchmarks/simple/simple.csproj, docs/articles/intro.md, examples/global/Program.cs, examples/hello/Program.cs, examples/memory/Program.cs, src/Engine.cs, src/EngineBuilder.cs, src/Host.cs, src/Store.cs, src/Wasmtime.csproj, tests/Fixtures/ModuleFixture.cs, tests/FunctionThunkingTests.cs, tests/GlobalExportsTests.cs, tests/GlobalImportBindingTests.cs, tests/InvalidModuleTests.cs, tests/MemoryExportsTests.cs, tests/MemoryImportBindingTests.cs, tests/ModuleLoadTests.cs, tests/TableExportsTests.cs, tests/TrapTests.cs, tests/WasiSnapshot0Tests.cs, tests/WasiTests.cs
The host was using the same store as was given in the constructor for the
underlying linker and defined memories/functions/globals.
As a result, a memory defined in a host, for example, would not get freed when
the host (and all instances) were disposed.
This prevents the use case where a module gets loaded once into a store and then
a host is created to instantiate the module.  If the operation to create the
host and instantiate the module is performed in a loop (e.g. a benchmark), then
memory continues to grow as the original store is never released.
=> Use a different store for the host.

src/Caller.cs, src/Externs/ExternFunction.cs, src/Externs/ExternGlobal.cs, src/Function.cs, src/Global.cs, src/Host.cs, src/Instance.cs, src/Interop.cs, src/Module.cs, src/MutableGlobal.cs, src/Table.cs, src/TrapException.cs, src/WasiConfiguration.cs, src/Wasmtime.csproj
With C# 8 brings NRT (Nullable Reference Types) which enforce nullability at compile time of reference types. This PR updates the signatures of method headers, properties, and other relevant data types to use NRTs where applicable to more clearly inform developers that certain return values may be null when they are not.
Perhaps the possibility of removing many of the manual null parameter checks could be accompanied for in this PR. Removing the nullability checks in methods yields (minor) performance gains, and removes lots of boilerplate from the codebase.
=> Use nullable reference types to annotate nullability

src/Externs/ExternFunction.cs, src/Function.cs, src/Interop.cs, src/Module.cs, src/WasiConfiguration.cs
In 2018, Span<T> and its friends were added to C#. This allowed developers to wrap various kinds of contiguous memory buffers (arrays, pointers, others) into a single data type. Its ability to slice allowed developers to very ergonomically prevent copying data, in a .NET way. This PR overhauls the existing public API to make use of Span<T> and friends.
For `Interop.InvokeCallback`, I would like feedback on why the object array was being allocated outside the invocation. This PR may need more inspection on that front, but for me on Windows all the tests pass.
In addition, DLL imports from the Interop class were modified from arrays to pointers, as it's a more "universal" datatype and understood the exact same. You can convert arrays into pointers easily, but you can't convert stackalloc'd …
=> Enhance array-based methods with Span<T> API

Directory.Build.props, README.md, docs/articles/intro.md, src/Wasmtime.csproj
This updates Wasmtime to 0.22.1 for a security fix for an upstream dependency
(smallvec).
=> Update Wasmtime to 0.22.1.

src/Wasmtime.csproj
Some companies rely on nuget licence data to automatically ensure they properly comply with the licence each library is released under
=> Add Nuget Licence Expression

tests/GlobalImportBindingTests.cs
Fix some of the tests given changes to upstream Wasmtime.
Imports need to be resolved prior to matching on the types now, so the tests
are updated to define the missing imports.
Additionally, the expected error message changed slightly.
=> Fix tests.

src/Config.cs, tests/MultiMemoryTests.cs
This commit adds the `WithMultiMemory` method to `Config` to enable support for
the multi-memory feature.
Fixes #65.
=> Add `WithMultiMemory` to `Config`.

src/Config.cs, tests/ConfigTests.cs
* The config-related enums should use `byte` as the underlying type as that is
what we're using in the P/Invoke signatures.
* Cut-and-paste error where `WithProfilingStrategy` was named as an overload to
`WithOptimizationLevel`.
* Added tests for setting the enums.
Fixes #72.
=> Small bug fixes for `Config`.

.github/workflows/main.yml, Benchmarks.sln, Examples.sln, benchmarks/simple/simple.csproj, examples/externref/externref.csproj, examples/funcref/funcref.csproj, examples/global/global.csproj, examples/hello/hello.csproj, examples/linking/linking.csproj, examples/memory/memory.csproj, examples/table/table.csproj, src/Value.cs, src/Wasmtime.csproj, tests/Wasmtime.Tests.csproj
The current build targets [ .Net Standard 2.1](https://github.com/bytecodealliance/wasmtime-dotnet/blob/19b3bccf841805481d2b657b0eb1b83a0a01b11f/src/Wasmtime.csproj#L4) in the main library and [.Net 5.0](https://github.com/bytecodealliance/wasmtime-dotnet/blob/19b3bccf841805481d2b657b0eb1b83a0a01b11f/tests/Wasmtime.Tests.csproj#L4) in the unit test library.
Microsoft announced [September 15th, 2020]( https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/) that .Net 5.0 replaced  .Net Standard 2.1 and with .Net 6.0, which is now the current LTS channel, replacing .Net 5.0 for which support officially ends in less than 3 months on [May 8, 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).
Additionally, the current build configuration also has a …
=> Upgrade to Dotnet 6.

.github/workflows/main.yml, Examples.sln, examples/consumefuel/Program.cs, examples/consumefuel/consumefuel.csproj, examples/consumefuel/consumefuel.wat, src/Caller.cs, src/Store.cs, tests/FuelConsumptionTests.cs, tests/ModuleFixture.cs, tests/Modules/FuelConsumption.wat
Here's a PR for https://github.com/bytecodealliance/wasmtime-dotnet/issues/106
* Added tests for existing Store fuel functionality, specifically AddFuel and GetConsumedFuel.
* Added a virtual method GetEngineConfig to the ModuleFixture class to add customized Engine configs.
* Added a pinvoke call to wasmtime_context_consume_fuel and wired that up through the Store.
* Added tests for the above.
* Added an example for consuming fuel.
=> Add fuel consumption tests and consume fuel

src/Caller.cs, tests/CallExportFromImportTests.cs, tests/Modules/CallExportFromImport.wat
Allows getting functions from Caller in the scope of imported function.
```csharp
linker.Define("env", "computeSha256", Function.FromCallback(store,
(Caller caller, int dataPtr) =>
{
var memory = caller.GetMemory("memory");
var data = ReadBytes(dataPtr, memory, caller);
var hash = SHA256.Create().ComputeHash(data);
var allocFunc = caller.GetFunction("alloc");
var hashPtr = (int) allocFunc.Invoke(store, hash.Length);
hash.CopyTo(memory.GetSpan(store).Slice(hashPtr, hash.Length));
}));
```
=> Added an ability to get function from Caller

tests/InvalidModuleTests.cs
Wasmtime upstream updated wasm-tools, which includes a tweaked error message
that caused a test failure.
This commit updates the message to fix the failing test.
=> Fix CI by updating an expected error message.

src/Config.cs
This PR fixes the .NET `Config` API to conform to the latest
upstream Wasmtime's C API signatures.
See bytecodealliance/wasmtime#4252 for the upstream change.
=> Fix changes to Wasmtime C API.

src/Config.cs, src/Engine.cs, src/Store.cs, tests/CallExportFromImportTests.cs, tests/ConfigTests.cs, tests/EpochInterruptionTests.cs, tests/Modules/Interrupt.wat
fixes: https://github.com/bytecodealliance/wasmtime-dotnet/issues/117
wasmtime removed and replaced old interruptability: https://github.com/bytecodealliance/wasmtime/commit/c22033bf9397e9bec3704ff10ca897598e3dcd08
also add a working unit test and features for this example: https://github.com/bytecodealliance/wasmtime/blob/main/examples/interrupt.c
=> add epoch interruption support

src/Value.cs
Removed a reference to `using System.Runtime.Intrinsics;` which I accidentally left in after experimenting with Vector128<byte>`. This is not needed and including it breaks source compatibility with Unity.
=> Removed Unnecessary Import

src/Global.cs, tests/GlobalImportBindingTests.cs
Used the same mechanisms implemented for type-safe/non-boxing functions to wrap `Global` in the same way. I expected this to take longer to implement, but everything just fell into place perfectly 🎉
=> Type-Safe/Non-Boxing Global

src/V128.cs
Added an `AsSpan` method to `V128` to allow for directly reading and writing the bytes of the `V128`. Without this `V128` is not very useful, since the value is inaccessible!
=> V128.AsSpan()

.github/workflows/main.yml, README.md, src/Wasmtime.csproj
This PR adds the wasmtime libraries for the following RIDs to the
`Wasmtime` package:
* linux-arm64
* osx-arm64
Fixes #135.
=> Add linux-arm64 and osx-arm64 runtimes to package.

src/Memory.cs, tests/MemoryExportsTests.cs
In my use of wasmtime I've often found myself doing something like this:
```csharp
var ptr = MemoryMarshal.Cast<byte, T>(_memory.GetSpan(Store!)[addr..]);
var v = ptr[0]; // Read
ptr[0] = new T(); // Write
```
to access a single value at an address.
I've added `Read<T>`, `Write<T>` and `GetSpan<T>` methods to `Memory` to make this pattern cleaner:
```csharp
var v = _memory.Read<T>(Store, addr);
_memory.Write<T>(Store, addr);
```
=> Generic Memory Methods

examples/memory/Program.cs, src/Caller.cs, src/Instance.cs, src/Linker.cs, src/Memory.cs, tests/FunctionTests.cs, tests/LinkerFunctionsTests.cs, tests/MemoryExportsTests.cs, tests/MemoryImportBindingTests.cs, tests/WasiTests.cs
Storing a reference to the `IStore` which was used to create the `Memory` object, this simplifies the API (all instance methods no longer need to be given an `IStore` reference) and removes a potential footgun (using the wrong `IStore`).
If you accept this PR then I can make the same change to `Function`, `Global` and `Table` as well.
=> Memory IStore Reference

examples/table/Program.cs, src/Instance.cs, src/Linker.cs, src/Memory.cs, src/Table.cs, tests/TableImportBindingTests.cs
Modified `Table` to keep a reference to the store which owns it. Much like #143 this simplifies the API and removes the potential footgun of trying to use a `Table` with the wrong `Store`
=> Table Store Reference

examples/global/Program.cs, src/Global.cs, src/Instance.cs, src/Linker.cs, tests/GlobalExportsTests.cs, tests/GlobalImportBindingTests.cs
Modified `Global` to keep a reference to the store which owns it. Much like #143 this simplifies the API and removes the potential footgun of trying to use a Global with the wrong Store
=> Global Store Reference

benchmarks/simple/Program.cs, examples/funcref/Program.cs, src/Caller.cs, src/Function.cs, src/Global.cs, src/Instance.cs, src/Linker.cs, src/ReturnTypeFactory.cs, src/Table.cs, src/Value.cs, src/ValueBox.cs, tests/CallExportFromImportTests.cs, tests/EpochInterruptionTests.cs, tests/ExternRefTests.cs, tests/FuelConsumptionTests.cs, tests/FuncRefTests.cs, tests/FunctionTests.cs, tests/GlobalImportBindingTests.cs, tests/LinkerFunctionsTests.cs, tests/MemoryImportBindingTests.cs, tests/TableImportBindingTests.cs, tests/WasiTests.cs
Modified Table to keep a reference to the store which owns it.
This required a change to the `ValueBox` and `ReturnTypeFactory` to take an `IStore` instead of a `StoreContext` (so that when a function is unboxed there's an `IStore` available to construct it).
=> Function Store Reference

benchmarks/simple/Program.cs, examples/consumefuel/Program.cs, examples/externref/Program.cs, examples/funcref/Program.cs, examples/global/Program.cs, examples/hello/Program.cs, examples/memory/Program.cs, examples/table/Program.cs, src/Instance.cs, src/Linker.cs, tests/CallExportFromImportTests.cs, tests/EpochInterruptionTests.cs, tests/ExitTrapTests.cs, tests/ExternRefTests.cs, tests/FuelConsumptionTests.cs, tests/FuncRefTests.cs, tests/FunctionTests.cs, tests/GlobalExportsTests.cs, tests/GlobalImportBindingTests.cs, tests/LinkerFunctionsTests.cs, tests/MemoryExportsTests.cs, tests/MemoryImportBindingTests.cs, tests/TableExportsTests.cs, tests/TableImportBindingTests.cs, tests/TrapTests.cs, tests/WasiTests.cs
Basically the same change as my previous 3 PRs, this time applied to the `Instance`. Removes another potential footgun of mixing up stores between instances.
=> Instance Store Reference

src/Function.cs, src/Result.cs, src/ReturnTypeFactory.cs, src/TrapException.cs, tests/FuelConsumptionTests.cs, tests/FunctionTests.cs, tests/Modules/Trap.wat, tests/TrapTests.cs
Created a new system to allow users of wasmtime-dotnet to create fully custom result types. This means that the library can ship a basic result type that fits 99% of usecases (just containing a `TrapException` object) and advanced users can build whatever they need for weirder usecases (e.g. making this work in Unity Jobs+Burst, which was my original goal for all this).
A custom result type implements one of two interfaces:
- `IFunctionResult<,,>`, this represents a return value from a function (approximately equivalent to `Result<Whatever, Trap>` in Rust)
- `IActionResult<,>`, this represents a return value from an action (approximately like returning `Option<Trap>` instead of `Result<(), Trap>` in Rust)
Unfortunately since `static abstract` methods aren't available yet (they're …
=> Trap result builders

src/Wasmtime.csproj
Hi!
As noted by @martindevans in https://github.com/bytecodealliance/wasmtime-dotnet/pull/160#issuecomment-1273516711, Unity up to version 2022.2 currently supports .NET Standard 2.1 (`netstandard2.1`, released with .NET Core 3.1) as highest .NET target framework. See [.NET profile support](https://docs.unity3d.com/2022.2/Documentation/Manual/dotnetProfileSupport.html) in the Unity documentation.
While the `net6.0` library apparently could also be used in Unity, it would break as soon as any feature/type introduced in a newer .NET version was used. Therefore, I think it would be a good idea to also build for .NET Standard 2.1 for the time being in order to support Unity users. Note that `Wasmtime` already builds successfully for `netstandard2.1` without any code change (at least when …
=> Add .NET Standard 2.1 (`netstandard2.1`) as target framework

src/Function.cs, src/Linker.cs, tests/ExternRefTests.cs, tests/FunctionTests.cs, tests/LinkerFunctionsTests.cs, tests/Modules/Functions.wat
Hi, this is a PR to fix the following issues when using `Function.FromCallback()` and `Linker.DefineFunction()`:
- Instead of invoking `callback.Method` (that may have a different parameter count than the callback), invoke the callback's `Invoke` method.
- Handle an `ITuple` return value only when `GetFunctionType()` determined that the function returns a tuple, to correctly return a boxed `ValueTuple` as `externref`.
- Support nested levels of `ValueTuple`s, so that it's possible e.g. to return a `ValueTulple<..., ValueTuple<..., ValueTuple<...>>>` (15 values).
Fixes #158
Fixes #159
Thank you!
=> Fix issues in `Function.FromCallback()` and `Linker.DefineFunction()`

tests/LinkerFunctionsTests.cs
In PR #161 I accidentally used `Linker.Define(..., Function.FromCallback(...))` instead of `Linker.DefineFunction()` for the new `LinkerFunctionTests` (Copy+Paste error... 😇) Sorry about that.
=> Correctly use Linker.DefineFunction() for the LinkerFunctionTests

src/Memory.cs, tests/MemoryAccessTests.cs, tests/Modules/MemoryAccess.wat, tests/Wasmtime.Tests.csproj
Hi, this PR adds new `Int64`-based APIs to `Memory` to allow to access memories with more than 32767 pages.
Fixes #165 
I added a new method `GetSpan<byte>(long address, int length)` as well as `GetSpan<T>(long address, int length)` to retrieve a `Span` starting at the given `Int64` address. Additionally, I added a `GetLength()` and `GetPointer()` methods for getting a raw pointer to the memory, and the memory length in bytes (in case you want to access the whole memory area at once, even if it exceeds a size of 2 GiB).
Additionally, for the `ReadXyz()`/`WriteXyz()` methods, I added new overloads taking an `Int64` address, and fixed the existing (`Int32`-based) methods to not throw an `OverflowException`.
I also added an `ObsoleteAttribute` to the `GetSpan()` method to indicate that it …
=> Allow to access a `Memory` with more than 32767 pages

src/Config.cs
Remove `CompilerStrategy.Lightbeam`.
The corresponding value (`WASMTIME_STRATEGY_LIGHTBEAM`) was removed with bytecodealliance/wasmtime#3390 (Wasmtime 0.31.0).
=> Remove `CompilerStrategy.Lightbeam`

src/TrapException.cs, tests/Modules/Trap.wat, tests/TrapTests.cs
The return type for native functions `wasmtime_trap_exit_status` and `wasmtime_trap_code` was incorrectly declared as `bool` without `[return: MarshalAs(UnmanagedType.I1)]`, which meant .NET marshaled the value as 4-byte `BOOL` instead of an 1-byte value.
For example, this caused `TrapException.Type` incorrectly being set to `TrapCode.StackOverflow` instead of `TrapCode.Undefined`, because the return value of `wasmtime_trap_code` was not correctly marshaled.
Fixes #171
Thanks!
=> Fix the `bool` return type declaration for native Trap functions

src/Config.cs, src/Export.cs, src/Import.cs, src/Memory.cs, tests/Memory64AccessTests.cs, tests/MemoryAccessTests.cs, tests/MemoryExportsTests.cs, tests/MemoryImportFromModuleTests.cs, tests/MemoryImportNoUpperBoundTests.cs, tests/MemoryImportWithUpperBoundTests.cs, tests/ModuleFixture.cs, tests/Modules/Memory64Access.wat, tests/Modules/MemoryAccess.wat
Hi, this PR adds support for 64-bit memories, by adjusting the APIs to match the C API introduced with bytecodealliance/wasmtime#3153 and bytecodealliance/wasmtime#3182.
It contains the following changes:
- Add `Config.WithMemory64()` for enabling the Memory64 proposal.
- Change properties/parameters in `Memory`, `MemoryExport` and `MemoryImport` that work with pages (like `Minimum`, `Maximum`, `Grow()`) to use a `long` instead of `uint`. (I chose `long` instead of `ulong` because memory pages cannot exceed `2**48`, and because `ulong` isn't CLS-compliant.)
(This will be a breaking change.)
- Added an `Is64Bit` property that specifies whether the memory is a 64-bit memory.
- Add tests to verify the new APIs added with #166 are able to access a memory beyond the 4 GiB area, and that the …
=> Add support for 64-bit Memory

src/Function.cs, src/TrapException.cs, src/WasmtimeException.cs, tests/Modules/Trap.wat, tests/TrapTests.cs
Hi, this PR implements the functionality to pass a .NET exception thrown at a wasm-to-host transition (.NET callback) (which means the exception is converted to a trap) as inner exception of the created `TrapException` when the trap bubbles up to the next host-to-wasm transition, by using a `ThreadStatic` (thread-local) field to temporarily store the exception until the stack is unwound.
That way, the original .NET exception that caused a trap can be retrieved from `TrapException.InnerException`, e.g. for debugging purposes.
If the exception thrown at the .NET callback is already a `TrapException`, we will not store that exception itself, but its `InnerException`, so that when the trap bubbles through multiple levels of wasm-to-host transitions, the `InnerException` at the root …
=> Pass original .NET callback exception as `TrapException`'s inner exception 

src/Wasmtime.csproj
Run the template commands (`dotnet tool t4`, introduced with #163) only once when building the project.
Otherwise, the commands would be run one time for each target framework (`netstandard2.1` and `net6.0`), which can sometimes cause file lock errors (and can degrade performance).
This is based on this StackOverflow answer: https://stackoverflow.com/questions/50071932/how-do-i-call-my-script-before-all-the-builds-for-only-once-in-a-multi-targeting/50080946#50080946 (similar to the existing target that downloads the `wasmtime` binary).
Thank you!
=> Run the template commands (`dotnet tool t4`) only once

tests/Memory64AccessTests.cs
This PR disables the 64-bit memory test as it consumes too much memory for CI to run reliably.
=> Disable 64-bit memory test for CI.

src/Caller.cs, src/Export.cs, src/Externs.cs, src/Function.cs, src/Import.cs, src/Linker.cs, src/Memory.cs, src/Module.cs, src/Table.cs, src/V128.cs, src/WasmtimeException.cs
Cleaned up some minor issues which were triggering warnings for me:
- Redundant nullability
- Redundant `unsafe` contexts
- Redundant `ToString` calls
Some other cleanup opportunities I did not include in this PR:
This method (and many others like it) does not need `unsafe`. Should I remove all of them? I've avoided touching anything marked `extern` so far.
There are many checked conversions from `nuint` to `int`. R# warns: `﻿Checked context is redundant: no operators or conversions with overflow checks`. I'm pretty sure this is an incorrect warning (e.g. see [this test here](https://dotnetfiddle.net/aamMPY)), but I just wanted to double check that before reporting it to Jetbrains.
=> Fixing Minor Code Quality Issues

src/Engine.cs, tests/ConfigTests.cs, tests/GlobalImportBindingTests.cs, tests/Modules/BulkMemory.wat, tests/Modules/MultiValue.wat, tests/Modules/SIMD.wat, tests/Modules/SharedMemory.wat
Added some more tests and fixed one small issue in the process:
- Modified `wasmtime_engine_increment_epoch` to return `void` instead of `IntPtr`. Based on signature from these docs: https://docs.wasmtime.dev/c-api/engine_8h.html
While writing the tests for the config I also came across an awkward error to do with disabling bulk memory. As documented [here](https://docs.wasmtime.dev/api/wasmtime/struct.Config.html#method.wasm_bulk_memory) if `Bulk memory = false` then it is required that `Reference Type = false`. If that is not the case then creating the engine throws this exception: `System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'`, with absolutely no indication of what is wrong.
I would like to modify `WithBulkMemory` to look like this: …
=> Improved Test Coverage.

src/Linker.cs
Fix definition of `wasmtime_linker_allow_shadowing` which was missing the `MarshalAsAttribute` (to marshal a `bool` as 1 byte instead of 4 bytes).
=> Fix definition of `wasmtime_linker_allow_shadowing`

src/Externs.cs
Remove fields from `ExternUnion` that were removed in the C API with bytecodealliance/wasmtime#3958.
This is a follow-up to #98.
=> Remove fields from `ExternUnion` that were removed in the C API

Examples.sln, src/Caller.cs, src/Store.cs, storedata/Program.cs, storedata/storedata.csproj, storedata/storedata.wat, tests/StoreDataTests.cs
closes #190 
This PR adds functionality to the `Store` and `Caller` that allows users to store arbitrary data in the WASM `Store` and access it using host functions like so:
```csharp
var storeData = "Hello, World";
var engine = new Engine();
var linker = new Linker(engine);
var store = new Store(engine, storeData);
linker.DefineFunction("", "store_data", (Caller caller) => {
var data = caller.GetData() as string;
Console.WriteLine(data);
});
```
TODO:
=> Implement bindings for StoreContext data

src/Linker.cs, tests/LinkerFunctionsTests.cs
Fix passing `name` as `module` in `TryGetExtern`
=> Fixed bug in linker TryGetExtern method

src/Export.cs, src/Global.cs, src/Import.cs, src/Memory.cs, tests/FunctionExportsTests.cs, tests/GlobalExportsTests.cs, tests/GlobalImportBindingTests.cs, tests/LinkerFunctionsTests.cs, tests/MemoryAccessTests.cs, tests/MemoryExportsTests.cs, tests/MemoryImportBindingTests.cs, tests/TableExportsTests.cs, tests/ValueBoxTests.cs
Added a number of tests.
In particular found one test which would crash the entire test runner (seems to be due to an access violation exception):
```csharp
[Fact]
public void ItFailsWithInvalidMutability()
{
var act = () => new Global(Store, ValueKind.Int64, 0, (Mutability)13);
act.Should().Throw<InvalidOperationException>();
}
```
This was caused by two things:
- Immediate problem was a missing check if the returned value is `IntPtr.zero` in this one particular case (added that check).
- Casting numbers into Mutability should not be possible. Replaced `Mutability` with a struct which has two predefined values (Mutable and Immutable). This should be _almost_ source compatible with the old enum - the only thing it does not allow is casting numbers into `Mutability`.
=> Yet more tests

src/Engine.cs, src/Function.FromCallback.cs, src/Function.FromCallback.tt, src/Function.cs, src/Global.cs, src/Instance.cs, src/Linker.cs, src/Memory.cs, src/Store.cs, src/Table.cs
Keep the `Store` alive until its `StoreContext` is no longer used.
As noted in https://github.com/bytecodealliance/wasmtime-dotnet/issues/200#issuecomment-1355191511, this is required (to handle the case when you forget to dispose the `Store`) as otherwise it could theoretically happen that the `Store` handle is deleted (with `wasmtime_store_delete`) in the GC finalizer thread even when at the same time a native call using the `StoreContext` handle is still executing in another thread, in case the `Store` object is no longer reachable.
For native methods taking a handle parameter that is passed as `SafeHandle`, this is not required as the `SafeHandle` is already kept alive during the call.
An exception is if you use `SafeHandle.DangerousGetHandle()` to retrieve the handle as pointer value …
=> Keep the `Store` alive until its `StoreContext` is no longer used

src/Caller.cs, src/Delegates.cs, src/Function.FromCallback.cs, src/Function.cs, src/FunctionCallbackOverloadTemplates.t4, src/Linker.DefineFunction.cs, tests/CallerTests.cs
~~**This builds on #213, merge that first**~~
Third time lucky?
Replaced `Caller` with a `ref struct`. With the reflection path stripped out and the removal of `IStore` this was a fairly simple change.
A few notable changes:
- Can't leak `Caller`, any breakage here is probably uncovering a bug.
- `Caller` is no longer disposable (we could add an empty `Dispose()` method and mark it `[Obsolete]`?).
Also this test:
```
[Fact]
public void ItCannotBeConstructedFromNullPointer()
{
var act = () => new Caller(IntPtr.Zero);
act.Should().Throw<InvalidOperationException>();
}
```
~~Did not compile because `act` is now a `CallerAction` instead of an `Action`, which is surprising change of `var` inference. Fixed by changing `var` to `Action`.~~ Never mind, see comment by kpreisser below.
Unlike my …
=> Ref struct caller

src/Memory.cs
All uses of this were removed in a recent PR, but the type itself remained.
=> Removed `TypeHandle`

.github/workflows/main.yml, benchmarks/simple/simple.csproj, examples/consumefuel/consumefuel.csproj, examples/externref/externref.csproj, examples/funcref/funcref.csproj, examples/global/global.csproj, examples/hello/hello.csproj, examples/memory/memory.csproj, examples/storedata/storedata.csproj, examples/table/table.csproj, src/Function.cs, src/Global.cs, src/Linker.cs, src/Memory.cs, src/Module.cs, src/Table.cs, src/Wasmtime.csproj, tests/Wasmtime.Tests.csproj
This PR fixes the definition of `wasmtime_linker_define` to match what is currently expected upstream.
As a result, items passed to `Linker.Define` must be associated with a store.
The internal `IExternal` interface was updated to expose the store associated with the item for `LinkerDefine` to use.
Also update the target framework to 7.0 (still `netstandard2.1` as well).
=> Fix the .NET API for recent Wasmtime C API changes.

src/Global.cs
Added `ToString` method for `Mutability` struct
=> Added `ToString` method for `Mutability` struct

src/Caller.cs, src/Memory.cs, tests/CallerTests.cs
This is one possible way to get access to `Memory` from a caller without any allocations. I think this is the simplest option (it's just one method) but the downside it doesn't give access to all of the convenience methods that are on `Memory`.
The other alternative I have come up with is to define a whole new `struct Memory` which has some/all of the `Memory` methods on it and the `class Memory` would just become a wrapper around that. That's a _much_ bigger change though!
Thoughts?
=> Caller.TryGetMemorySpan

src/Caller.cs
Changed the string length measurement to use `GetByteCount` instead of `GetMaxByteCount` to get a more precise measurement. See [this review](https://github.com/bytecodealliance/wasmtime-dotnet/pull/219#pullrequestreview-1299001693) by @kpreisser for context.
=> More Precise String Length

src/Linker.cs
- Added public `Define` methods for all externs.
- Removed method which accepted an `object` parameter and dynamically checked that it was an extern.
As discussed in https://github.com/bytecodealliance/wasmtime-dotnet/pull/224#issuecomment-1433591490
=> Extern define

src/Caller.cs, src/Linker.cs, src/TemporaryAllocation.cs
~~Builds on #228, review/merge that first!~~ (That has been merged now).
While working on #228 I came up with this idea for replacing the ad-hoc approaches to string->UTF8 conversions that we have around the place at the moment.
Currently we're either doing this simple approach that always allocates:
```csharp
Encoding.UTF8.GetBytes(a_string); // Always allocates
```
Or this slightly more complex approach that sometimes allocates:
```csharp
var nameLength = Encoding.UTF8.GetByteCount(name);
var nameBytes = nameLength <= StackallocThreshold ? stackalloc byte[nameLength] : new byte[nameLength]; // Sometimes allocates
Encoding.UTF8.GetBytes(name, nameBytes);
```
Or even this (😱) approach which never allocates:
```csharp
byte[]? nameBytesBuffer = null;
var nameLength = …
```
=> Better temporary memory

src/Caller.cs, src/Instance.cs, src/Linker.cs, src/Store.cs, src/Value.cs, src/ValueBox.cs, src/ValueRaw.cs, tests/CallerTests.cs
Added caching to the `Store` for `Function` and `Memory` objects. The `Caller` uses this to retrieve `Function`/`Memory` objects, this saves allocating lots of objects in caller contexts.
This is an alternative to #233 and #224. I prefer this approach to #233 since it gives access to the entire `Function` API, instead of a tiny subset exposed through the `Caller`. I prefer it to #224 since the `Memory` object remains a class instead of becoming a struct, which is more idiomatic.
=> Caller Function Cache

src/Function.Wrap.cs, src/Function.Wrap.tt, tests/FunctionTests.cs, tests/Modules/Functions.wat
Added a cache to `Function` which stores wrapped function. This allows Wrap to be called multiple times without lots of allocations of the same thing.
This will work well with #235 - a `Caller` can ask for a `Function` object (cached) and then wrap it (cached) and then call it, all without allocating anything 🥳
=> Function Wrapper Cache

src/Global.cs, tests/GlobalImportBindingTests.cs
Added a cache for the Global type safe accessor, similar to the wrapped function cache introduced #236.
=> Added a cache of the Global.Accessor

src/Instance.cs, src/Store.cs
We already have `Function` and `Memory` objects in the `Store` cache, this adds `Global` objects too.
=> Added a cache of `Global` objects in the `Store`

src/Function.cs, src/Value.cs, src/ValueRaw.cs
Adapt to changes in bytecodealliance/wasmtime#6338, which changes the type of raw funcrefs/externrefs from `usize` to `void*`.
Therefore we change `nuint` to `IntPtr` for these types, which although technically equivalent (except for the signed/unsigned behavior), better matches the native API.
=> Change raw funcref/externref from `nuint` to `IntPtr`

src/Store.cs, tests/StoreTests.cs
Implemented `Store.SetLimits` using the new `wasmtime_store_limiter` function.
=> Implemented `Store.SetLimits`

.github/workflows/main.yml
This PR is an attempt to work around flakiness in the Windows CI relating to downloading Wasmtime release assets.
See https://github.com/actions/runner-images/issues/7007.
=> Change to use `windows-2019` to fix CI.

src/Config.cs, tests/ConfigTests.cs, tests/Modules/RelaxedSIMD.wat
Added a new config method `WithRelaxedSIMD(bool enable, bool deterministic)` which enables relaxed SIMD (introduced in https://github.com/bytecodealliance/wasmtime/pull/5892, exposed to c-api in https://github.com/bytecodealliance/wasmtime/pull/6292)
=> Added Relaxed SIMD

examples/table/Program.cs, src/Table.cs, src/Value.cs, tests/StoreTests.cs, tests/TableExportsTests.cs, tests/TableImportBindingTests.cs
Replaced `ValueKind` with `TableKind` in `Table`. This properly represents the range of type a `Table` may contain. I've minimised the amount of breakage by still accepting `ValueKind` in the constructor (marked with an `Obsolete` attribute, to steer peope towards the new constructor).
This is a small improvement (it provides a hint at valid table types) but it is still a bit fragile. It's very easy to use an incorrect `Kind` or to pass an incorrect type into `SetElement`. We may want to improve on that in the future (e.g. type safe table wrappers, like we have for globals).
=> Added `TableKind` for tables

src/Wasmtime.csproj
Removes dependency on having unzip in path
**How did I test it?**
The only test I have run is on Windows 11 building under Powershell 7.3.5
```powershell
PS> dotnet build .\Wasmtime.sln
```
If your CI does not handle the other platforms then let me know if you feel additional testing is needed on my side.
Fixes #266
=> Replace Exec task with Unzip task

tests/ConfigTests.cs, tests/MultiMemoryTests.cs
Fix failing tests after the changes in bytecodealliance/wasmtime#7285.
Since that change, `threads`, `multi-memory`, and `relaxed-simd` are enabled by default. E.g. disabling `bulk-memory` also requires disabling `threads`, and disabling `simd` also requires disabling `relaxed-simd`.
=> Fix failing tests after the changes in bytecodealliance/wasmtime#7285

examples/consumefuel/Program.cs, src/Caller.cs, src/Store.cs, tests/CallerTests.cs, tests/FuelConsumptionTests.cs
Update to the new fuel APIs introduced in bytecodealliance/wasmtime#7298.
I switched to a property so that it's possible e.g. to add or consume fuel with code like this:
```cs
store.Fuel += 100;
// Consume fuel, throwing an OverflowException if too little fuel is available.
checked {
store.Fuel -= 150;
}
```
What do you think?
Thanks!
=> Update to the new fuel APIs

src/Linker.DefineFunction.cs, src/Linker.DefineFunction.tt, src/ValueRaw.cs, tests/FunctionTests.cs, tests/LinkerFunctionsTests.cs
Added support for defining functions which have a tuple as a generic parameter.
Previously defining like this would work:
```csharp
Linker.DefineFunction<int, int, int>("module", "name", (int a) => (a, a));
```
But doing this would _not_ work:
```csharp
void DefineWrapper<TIn, TOut>(Func<TIn, TOut> func)
{
Linker.DefineFunction<TIn, TOut>("module", "name", func);
}
DefineWrapper<int, (int, int)>((int a) => (a, a));
```
Even though they're ultimately doing the same thing, just with one more level of generic typing.
This PR detects that case and adds limited support for tuples (only up to 4 elements).
I have **not** added support for `ValueRaw` unboxing of tuples. As far as I can tell it's not required anywhere.
=> Added support for Linker.DefineFunction with generic tuples

src/Instance.cs
Removed a use of `GetBytes` in `Instance.TryGetExtern` and using a stack buffer instead.
=> Less Allocation In `Instance.TryGetExtern`

src/Config.cs, src/Engine.cs, src/Module.cs, src/Store.cs, tests/ConfigTests.cs, tests/EngineTests.cs, tests/ModuleLoadTests.cs, tests/StoreTests.cs
Some previous relevant discussion: https://github.com/bytecodealliance/wasmtime-dotnet/pull/288#issuecomment-1861032709
The handles in wasmtime-dotnet never seem to be made invalid, so the IsInvalid checks seem to be useless. I've added `IsClosed` checks onto all the places that `IsInvalid` is used.
Previously all these paths were untested, added new tests which cover these paths.
=> `handle.IsClosed` Checks

src/Function.FromCallback.cs, src/Function.FromCallback.tt, src/FunctionCallbackOverloadTemplates.t4, src/Linker.DefineFunction.tt, src/Store.cs
Optimisations based on profiling a simple program that loops and makes 10M calls back into C#. Runtime of this test program was 350ms initially. Test program is here: https://gist.github.com/martindevans/0e0f334bc095808b81c13dedde6c80c1
`FromCallback` has been modified to use the store initially used to create the callback, instead of retrieving it from the caller context. In cases where the `Caller` is not required this skips creating the `Caller` (in turn skipping a call to `wasmtime_caller_context`) and skips accessing the store from the caller (in turn skipping `GCHandle.FromIntPtr` to retrieve the `Store` object). Overall this reduced the total execution time down from 350ms to 272ms.
`Store` has been modified to fetch the `contextHandle` when first created. The docs …
=> Optimisations On 10M Calls

src/Instance.cs, tests/InstanceTests.cs
Added methods to fetch all exports from an Instance, using `wasmtime_instance_export_nth` to enumerate exports.
Also removed `wasmtime_instancetype_delete`, since it doesn't appear to be part of the c-api any more.
=> Instance Get All Exports

src/Config.cs
Added `WithMacosMachPorts` config option
=> Added `WithMacosMachPorts` config option

Directory.Build.props, src/Wasmtime.csproj
replaces #317 by only making this update to the release branch
=> Prep for release of v20.0.2

src/Externs.cs, src/Function.cs, src/Global.cs, src/Store.cs, src/Table.cs, src/Value.cs, src/ValueRaw.cs, tests/ValueBoxTests.cs
Update to recent Wasmtime C API changes regarding values.
This includes updates for:
- bytecodealliance/wasmtime#8011
- bytecodealliance/wasmtime#8451
- bytecodealliance/wasmtime#8461
TODOs:
**Note:** The `anyref` type is not yet supported; it was introduced by the [GC Proposal](https://github.com/WebAssembly/gc/blob/main/proposals/gc/Overview.md). Support for this type can be added separately, after deciding how the API should look like.
Fixes part of #315 (the WASI part is fixed by #316).
=> Update to recent Wasmtime C API changes regarding values

Directory.Build.props, README.md, src/Wasmtime.csproj
This also makes it only one place where the version needs updated. I tested this locally and it prints the right version in the `nuspec`:
```
<releaseNotes>Update Wasmtime to 21.0.1.</releaseNotes>
```
=> Bump version to 21.0.1

src/WasiConfiguration.cs
Fixed breakage due to changes introduced in https://github.com/bytecodealliance/wasmtime/commit/e55fa3cc928547a88738597cb6236d8571c42501
Obviously I can't run all the tests, due to the other changes mentioned here https://github.com/bytecodealliance/wasmtime-dotnet/issues/315#issuecomment-2182893613. Here's what I could run:
The WasiTests cover the changed code.
=> Fix Some C-API calls

src/Externs.cs, src/Store.cs
Revert the changes to the cache of externs in `Store` from #318, as those would have negative performance impact.
When looking up a value in the dictionary, it would use the `Equals(object)` method on the struct which causes the struct to be boxed. Additionally, the default `ValueType.GetHashCode()` apparently doesn't incorporate the value of `[U]IntPtr`/`n[u]int` fields, so we would also need to implement `GetHashCode()` in the `Extern...` structs.
Instead, we use a `ValueTuple` as key consisting of the extern type and the the both struct fields, like it was done previously (`ValueTuple<...>` implements `IEquatable<T>` to avoid boxing, and uses all elements for calculating the hash code).
It should be Ok to access the `__private` field of the `Extern...` structs, because we don't …
=> Revert the changes to the cache of externs in `Store`

src/Wasmtime.csproj
Wasmtime recently completed Windows ARM64 support with bytecodealliance/wasmtime#9266 and added release artifacts with bytecodealliance/wasmtime#9283. This PR adds the Windows ARM64 Wasmtime binary to `wasmtime-dotnet`.
I think it should be available starting with Wasmtime 26.0.0.
Fixes #298
=> Add Wasmtime Windows ARM64 (AArch64) binary

src/Instance.cs
* Fix similar Instance.GetFunctions(), GetTables(), GetGlobals() methods
GetMemories() returned empty list for following code but worked fine after swapping 2 exports:
(module (type $t0 (func)) (func $run) (memory $0 1)
(export "run" (func $run))
(export "memory" (memory 0))
)
=> Fix Instance.GetMemories() ignored memories after the 1st non-memory export
