bytecodealliance/wasmtime-dotnet

src/Externs/ExternTable.cs
src/Externs/Externs.cs
tests/TableExportsTests.cs

Fixes #17
Include table exports into the Externs instance

Added table exports to Externs

---

README.md
examples/externref/Program.cs
examples/funcref/Program.cs
examples/global/Program.cs
examples/hello/Program.cs
examples/memory/Program.cs
examples/table/Program.cs

* Fix README example explanation.
* Change namespace used in examples to something generic.

Miscellaneous example fixes.

---

tests/TableImportBindingTests.cs

Update an expected exception message that changed upstream.

Fix tests.

---

.github/workflows/main.yml
examples/linking/name.wat
examples/linking/program.wat
src/Externs/ExternModule.cs
src/Function.cs
src/Interop.cs
src/Module.cs
tests/ModuleLinkingTests.cs

This PR updates the interop signatures for several C API functions that
have been updated in current Wasmtime.
This should turn the CI green.

Fix CI with latest Wasmtime.

---

tests/InvalidModuleTests.cs
tests/MultiMemoryTests.cs

This PR fixes the nightly CI failure.

Update test expected error messages with latest Wasmtime builds.

---

src/Module.cs
tests/InvalidModuleTests.cs
tests/ModuleLoadTests.cs
tests/ModuleSerializationTests.cs

This PR implements module serialization and deserialization.
It also adds a `Module.Validate` method.

Implement module serialization and deserialization.

---

tests/TrapTests.cs

This commit fixes the unit tests to expect an updated trap message.

Fix unit tests.

---

src/Wasmtime.csproj

https://github.com/bytecodealliance/wasmtime-dotnet/issues/92

enabled source link support

---

src/Config.cs
tests/ConfigTests.cs

Closes https://github.com/bytecodealliance/wasmtime-dotnet/issues/109 once https://github.com/bytecodealliance/wasmtime/pull/4154 will be included into next released

Added Nan Canonicalization config

---

src/ReturnTypeFactory.cs
src/V128.cs

Two more very minor changes to improve source compatibility with Unity.

more_unity_fixes

---

src/Module.cs

Added `Wat2Wasm` method, exposing the wasmtime `wat2wasm` function.

Module.Wat2Wasm

---

Directory.Build.props

You know, the file that actually bumps the artifact versions 🙄

Add missing file from version bump.

---

README.md
docs/articles/intro.md

This commit removes a note in the README mentioning that the package is currently prerelease.

Remove note in README.

---

src/AssemblyAttributes.cs
src/ValueBox.cs
tests/StoreFixture.cs
tests/ValueBoxTests.cs

Improved test coverage on `ValueBox` and also `Value`, converting from various values into other values (both valid and invalid). No bugs found.

More Unit Tests

---

tests/CallerTests.cs
tests/Modules/Caller.wat

Since I'm investigating changing the Caller mechanism I wanted some test coverage first. 100% coverage on `Caller`, No issues found.

Caller Unit Tests

---

examples/consumefuel/Program.cs
examples/externref/Program.cs
examples/funcref/Program.cs
examples/global/Program.cs
examples/hello/Program.cs
examples/memory/Program.cs
examples/storedata/Program.cs
examples/table/Program.cs
src/README.md
src/Wasmtime.csproj

This PR fixes the package README to not include the custom HTML present in the repo README, as NuGet.org doesn't support rendering the HTML.
This commit also removes a `Main` declaration in the examples in favor of top-level statements.
Fixes #217.

Fix package README.

---

src/Config.cs

Add PerfMap profiling support (`ProfilingStrategy.PerfMap`).
See bytecodealliance/wasmtime#6030

Add PerfMap profiling support

---

src/Instance.cs

Removed `TypeHandle` in `Instance` since it wasn't used anywhere.

Removed Instance.TypeHandle

---

src/Function.Wrap.cs
src/Function.Wrap.tt

Made `allocCount` const where possible.

const `allocCount` in Function wrapper

---

tests/Wasmtime.Tests.csproj

⬆️ Nuget Packages for test project

⬆️ Nuget Packages for test project

---

.github/workflows/main.yml

Upgrade action in main.yml to no use deprecated environment

---

Directory.Build.props

Updates the package to use the latest wasmtime release
fixes #306

Update to wasmtime 22.0.0
